.PHONY: build debug test bench benchalloc coverage

build:
	./cmd.sh build
debug:
	./cmd.sh debug
test:
	./cmd.sh test
bench:
	./cmd.sh bench
benchalloc:
	./cmd.sh benchalloc
coverage:
	./cmd.sh coverage
